_chair = _this select 0; 
_unit = _this select 1;
_chair setVariable["occupied",true,true]; 
//[[player,"Crew"],"noaim_fnc_animSync",true,false] spawn noaim_fnc_LAST;
[player,"Crew"] remoteExec ["noaim_fnc_animSync",-2];
waitUntil {animationState player == "crew"};
_unit setPos (getPosATL _chair); 
_unit setDir ((getDir _chair) - 180); 
life_action_standup = _unit addaction ["<t color='#0099FF'>Aufstehen</t>","scripts\chair\standup.sqf"];
life_sitting_chair = _chair;
_unit setposatl [getPosATL _unit select 0, getPosATL _unit select 1,((getPosATL _unit select 2))];